<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Produk</name>
   <tag></tag>
   <elementGuidId>9154e3f8-0c88-4f4c-ae31-6f5fefbc2dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/div/a[5]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a0dd24bd-6476-4a6d-bb81-e3b4a03a0e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Produk</value>
      <webElementGuid>62a35a93-9dc4-4b64-a2e8-e0771f7dc918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;left&quot;]/div[@class=&quot;menu&quot;]/a[@class=&quot;link&quot;]/p[1]</value>
      <webElementGuid>5d99c4c0-c75d-463d-a9fb-a0522706f6e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div/a[5]/p</value>
      <webElementGuid>fc0135bb-eafd-4c0d-8371-15f4205a30d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::p[6]</value>
      <webElementGuid>28bc5a7b-fd16-4db5-8108-2c7d9ce277e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total pendapatan di bulan ini'])[1]/preceding::p[8]</value>
      <webElementGuid>c48118fa-1001-4b86-ada6-d466462f5693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Produk']/parent::*</value>
      <webElementGuid>3c8daf4d-1e75-4744-96a6-45a7796e4d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/p</value>
      <webElementGuid>2cdb1082-5360-43bc-be78-64d5f9ac9c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Produk' or . = 'Produk')]</value>
      <webElementGuid>c30238ec-0f28-4c18-839d-7ad7cf040f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
