<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ProdukTagihanTop UpListrikKesehatanE_35fa38</name>
   <tag></tag>
   <elementGuidId>ca5293d5-c06b-43a0-8c9d-2a85650a256c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='category']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;category&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6a904973-dd8d-498f-bb28-cb8c2fa8a9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62c810e7-41e4-4c36-be6d-534b35e75286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>e81ac2a8-08d2-48ea-92ce-706eaa3d3181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProdukTagihanTop UpListrikKesehatanEntertainmentPulsaPaket Data</value>
      <webElementGuid>f11996e3-accc-413c-866b-14ad28f9d5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;rewardSection&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;topRight&quot;]/select[@class=&quot;input&quot;]</value>
      <webElementGuid>4f9e405d-e653-4f8c-8a3f-0c5eba60572c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='category']</value>
      <webElementGuid>cd02612c-1c8e-4b57-9b57-ea9e481302f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/div[2]/select</value>
      <webElementGuid>cf8a9788-7ece-4566-8c05-1758a6ece1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reward Koin Transaksi'])[1]/following::select[1]</value>
      <webElementGuid>be02de33-5352-4574-a73e-17415fec4ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::select[1]</value>
      <webElementGuid>fe11c5e4-9de5-49b3-8faf-68aff4a3dfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[3]/preceding::select[1]</value>
      <webElementGuid>80876387-6e03-4cdc-ad86-85b61c5fd784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[2]/preceding::select[1]</value>
      <webElementGuid>50a1302a-d8b6-424f-80df-fbb149c84859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6d58b6eb-89a8-4381-bcbb-a0755b6ac69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'category' and (text() = 'ProdukTagihanTop UpListrikKesehatanEntertainmentPulsaPaket Data' or . = 'ProdukTagihanTop UpListrikKesehatanEntertainmentPulsaPaket Data')]</value>
      <webElementGuid>24e3e7d0-2704-49db-b461-4744187d8fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
