<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Produk_produk</name>
   <tag></tag>
   <elementGuidId>fa95290e-8f74-484a-b123-34ffcab45b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;produk&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='produk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>1d17846c-77c7-4fba-853d-94821c735921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>b844f0e0-7c82-41ea-9968-90c44bc2fb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>8a13d18f-8dbf-486f-8e24-2eef359fa022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>75da4cd6-9234-42c2-8bd1-0b2ce7d977ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>5b8bff47-411d-463d-89b7-5c4efc6ea63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>f4396261-9f07-4137-9ca8-8073dadd20ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>f011da0e-3508-4191-ad62-58576b53e6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/form/div[1]/input</value>
      <webElementGuid>d9dbbfd0-c090-4df1-a136-f826612d62ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='produk']</value>
      <webElementGuid>024ab00e-b5c1-4d7d-9352-9ffc709013b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/form/div/input</value>
      <webElementGuid>f710b690-d3f2-4c00-8078-ce5643ab3fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e07ae691-f3c4-41c2-81f3-0860b85883ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tambahkan Nama Produk Anda...' and @name = 'produk']</value>
      <webElementGuid>6039868e-fa5d-4f9f-9c06-87e8bf51748c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
