<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_homepage</name>
   <tag></tag>
   <elementGuidId>75052b8d-7bda-4776-97ab-c27a9619ef9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;header_container&quot;]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;header_container&quot;]/div[2]/span</value>
      <webElementGuid>bd4f0991-192f-4cc8-8213-01e50f4fe269</webElementGuid>
   </webElementProperties>
</WebElementEntity>
