<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fiturnya apa aja_aos-init aos-animate</name>
   <tag></tag>
   <elementGuidId>3767479f-d292-4e8c-be62-158288e9cb4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.center > img.aos-init.aos-animate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='fitur']/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a6a91676-4097-456e-b26c-da19435e39ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aos</name>
      <type>Main</type>
      <value>fade-down-right</value>
      <webElementGuid>695d2cd1-ab5e-49e3-b238-5e014a2e100e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aos-duration</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>8fc698f5-da42-4396-bfb1-19eea75e681e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/phone.3180bf94b7e28283dca3058bb90692a1.svg</value>
      <webElementGuid>bcf351a2-6884-4930-991f-afca4c41bb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>2d5ec921-c5f2-408f-915b-1b483b5d4ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aos-init aos-animate</value>
      <webElementGuid>3484e55f-cbee-43c8-bb85-142ae649eace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitur&quot;)/div[@class=&quot;center&quot;]/img[@class=&quot;aos-init aos-animate&quot;]</value>
      <webElementGuid>735d8b6d-a46f-434a-90a6-7ca551bf0969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='fitur']/div[2]/img</value>
      <webElementGuid>76b75eb3-6d82-48a2-90ff-738625bbce83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='phone'])[2]</value>
      <webElementGuid>b6aa775f-08cd-4d69-97c2-b9e476992ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]/img</value>
      <webElementGuid>21e26b29-7b95-45a1-9211-de22b26d95b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/phone.3180bf94b7e28283dca3058bb90692a1.svg' and @alt = 'phone']</value>
      <webElementGuid>6f4f39e4-d9bf-40d1-8a9a-9c1211aa7cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
