<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yakin_1</name>
   <tag></tag>
   <elementGuidId>a94dfa8f-a358-43bf-96c7-70cfd076a5b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/div/div/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section[1]/div/div/div/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section[1]/div/div/div/button[1]</value>
      <webElementGuid>4b99f1d5-9d68-4fbf-bdbe-6bdfc9c40d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div/div/div/button</value>
      <webElementGuid>9d6f1348-a524-4511-bad9-6c808ff3fc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda yakin ingin menghapus agen?'])[1]/following::button[1]</value>
      <webElementGuid>1515ae4a-5ffe-4d62-a2b5-498998d16c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::button[1]</value>
      <webElementGuid>e0596e53-d69d-4650-97d0-82ac9abdd08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::button[1]</value>
      <webElementGuid>102a4266-94b5-406d-b27e-427b17861147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agen'])[2]/preceding::button[2]</value>
      <webElementGuid>bb8b7812-eb26-4bd9-b6fb-f11f58b64983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yakin']/parent::*</value>
      <webElementGuid>d3834ad2-ca97-4c0a-bfbe-53a9fa269e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b7697d96-49be-4f82-a9c9-63de48de46a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Yakin' or . = 'Yakin')]</value>
      <webElementGuid>240cd448-5e8f-481f-8234-832c4711040d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
