<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button</name>
   <tag></tag>
   <elementGuidId>94d55e10-2c0a-4760-a480-ea4e874a3001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[7]/td[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb62b145-f2c9-49dc-9730-31f617659027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;kategoriSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[7]/td[2]/div[1]/button[1]</value>
      <webElementGuid>bad5077f-edfe-40ca-9ae2-f2b6e4dff6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54b81886-0ddd-4560-9819-da4539131f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;kategoriSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[7]/td[2]/div[1]/button[2]</value>
      <webElementGuid>77e36c5b-5071-46dd-902b-1f321d55f004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[7]/td[2]/div/button</value>
      <webElementGuid>ef0bd8db-960a-463d-866b-5e001da724dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[2]/following::button[1]</value>
      <webElementGuid>0c86ea0e-21e3-4d80-90df-6fb2171fcaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[1]/following::button[3]</value>
      <webElementGuid>7ace816e-dfe3-4958-ac34-9c9eac82701a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[7]/td[2]/div/button</value>
      <webElementGuid>39d7c881-4769-41a5-ba44-1f74a3aa5340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[7]/td[2]/div/button[2]</value>
      <webElementGuid>8fc41e04-2d8f-4d01-92b5-9a63db37156f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[2]/following::button[2]</value>
      <webElementGuid>49b175a5-557b-4073-b747-06c49e416a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[1]/following::button[4]</value>
      <webElementGuid>0a6aeb79-9710-47e4-99fe-dd0f6f32487f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[7]/td[2]/div/button[2]</value>
      <webElementGuid>7d88f80d-718d-446b-9a1e-2870ab5d8fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
