<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_2amrilrisman1 GB 1 Hari Pengguna By.U20M_e042ee</name>
   <tag></tag>
   <elementGuidId>8dd7ec44-8ca8-411f-8661-a6932b7550ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[2]/tr</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>0ccf77fc-e615-4b7c-aba3-9b746a7e9468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2amrilrisman1 GB 1 Hari Pengguna By.U20Mon Dec 19 2022 22:42:10SUCCEEDED</value>
      <webElementGuid>36428b55-490a-432f-86cc-3f8eebb03330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;agenSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[2]/tr[1]</value>
      <webElementGuid>dd37bc5a-7cd6-48c0-957c-db3d89a47f38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[2]/tr</value>
      <webElementGuid>2f5b26a8-aed3-4c01-87e7-be56891b4d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENDING'])[1]/following::tr[1]</value>
      <webElementGuid>a6ac06d5-b2b6-4efe-911b-600fd995a7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon Dec 19 2022 22:41:33'])[1]/following::tr[1]</value>
      <webElementGuid>47d46b28-24c5-4dea-9965-2b2b13530ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/tr</value>
      <webElementGuid>232e5fdf-574e-46b3-a769-01c3ae41d5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[(text() = '2amrilrisman1 GB 1 Hari Pengguna By.U20Mon Dec 19 2022 22:42:10SUCCEEDED' or . = '2amrilrisman1 GB 1 Hari Pengguna By.U20Mon Dec 19 2022 22:42:10SUCCEEDED')]</value>
      <webElementGuid>dd7cdf5d-3cb6-4aac-b397-53120c958fd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
