<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>b55aa3e7-bbea-4bff-8715-714bb82dacb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[4]/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bfa56718-bdda-4a47-aa50-b071b225b674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;agenSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[4]/td[7]</value>
      <webElementGuid>fcb6ef4a-898b-4a7d-a0f0-e1865b1f2625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cbe65e7c-1587-44bc-86dd-952b57ba4a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;agenSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[5]/td[7]</value>
      <webElementGuid>44e89631-7273-4a93-bb4f-96cf62c9a633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[4]/td[7]</value>
      <webElementGuid>772dae56-54fc-4e8d-b3ec-506e180d3cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='amrilrismanto@gmail.com'])[2]/following::td[3]</value>
      <webElementGuid>22768c58-44f8-4c99-8c6b-9b6b411ab47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun Dec 11 2022 21:26:09'])[1]/following::td[4]</value>
      <webElementGuid>a09ff9e8-a8de-40f3-bdb7-eb0f111d76c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[4]/td[7]</value>
      <webElementGuid>31a44ea8-9e96-4ba7-a62c-c5d3066f5b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[5]/td[7]</value>
      <webElementGuid>56b1a583-50af-438e-ab94-e156bac2fd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alterra5capstone@gmail.com'])[2]/following::td[3]</value>
      <webElementGuid>ef29a21a-a963-44cf-8214-cb7a7587beb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wed Dec 14 2022 06:11:27'])[1]/following::td[4]</value>
      <webElementGuid>939afe93-3029-436e-8295-c7f3801aa0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[5]/td[7]</value>
      <webElementGuid>cf4d4b9d-5ce2-4d4c-b761-a2956a41112e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
