<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>cf3add74-8796-44ed-b3a2-b56ecf27ea70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logosidebar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38e21cbe-6ceb-4ab3-80b3-3d29ca6a65ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/logosidebar.861b1dd07bdb37387f0a9d1e007fc2ba.svg</value>
      <webElementGuid>d5bdd2cd-a91f-4169-b882-74675a920b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logosidebar</value>
      <webElementGuid>72215cae-b4a5-4681-955c-00d131ef219d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;left&quot;]/img[1]</value>
      <webElementGuid>2d73e4b1-70c1-4cc0-8530-26a0fbe0457f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/img</value>
      <webElementGuid>7966575b-dbe5-469b-83c0-7b172ef63fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logosidebar']</value>
      <webElementGuid>a562a898-c44c-40c2-ba26-515bb5a15e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f2cd287c-c961-4de3-bf06-00b856cc79f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/logosidebar.861b1dd07bdb37387f0a9d1e007fc2ba.svg' and @alt = 'logosidebar']</value>
      <webElementGuid>fde91e10-2a6d-4198-9438-a4342a7c1deb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
