<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Koin Transaksi_coins</name>
   <tag></tag>
   <elementGuidId>7e745456-7547-4cf4-a686-576c6204dc54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='coins']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;coins&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b30850f-f1f3-4b0d-8db5-b6ffdac789bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>369974e4-33af-4947-a91f-ef51fb71ffb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Koin Transaksi</value>
      <webElementGuid>9b99e9f7-a4ce-4b7d-88f3-a0fea0014bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>coins</value>
      <webElementGuid>75611bba-eb70-45d5-97ab-7fee9aaa4c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>fa5a6557-3a4d-44eb-be7a-c4a1a7d0a077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;input_row&quot;]/div[@class=&quot;componentInput&quot;]/input[1]</value>
      <webElementGuid>56d54804-0bdc-4a0b-adec-cb05e2d27b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='coins']</value>
      <webElementGuid>d94f74d7-a6ff-4702-9677-2c529693dad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/form/div[6]/div[2]/input</value>
      <webElementGuid>609300bc-46c3-4a0a-8ea7-c30a2e6a5b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>893dca90-cbb8-481d-9033-8059b8b1b783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Koin Transaksi' and @name = 'coins']</value>
      <webElementGuid>6f98b91a-3688-4d85-8992-939252aae13b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
