<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button</name>
   <tag></tag>
   <elementGuidId>85e1c1c8-f6d2-4f1c-8a4f-622ca3ac8f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/div[3]/table/tbody[2]/td[5]/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>015b5615-b8ea-43a5-944b-70b67ecfb1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;rewardSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[2]/td[5]/div[1]/button[2]</value>
      <webElementGuid>36dfd29c-28cd-4d98-be87-7adadda21ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>615d3ea2-40c8-4e89-a13a-2e3041307e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;rewardSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[1]/td[5]/div[1]/button[2]</value>
      <webElementGuid>0346b87b-f25d-4042-8e2b-ed8fcb0695a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[3]/table/tbody[2]/td[5]/div/button[2]</value>
      <webElementGuid>c0beca0c-6f73-4b99-8a6c-17135c98d2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulsa'])[3]/following::button[2]</value>
      <webElementGuid>f7d452c6-5362-42e7-aee0-83bb2e1c47c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freedom 100.000'])[1]/following::button[2]</value>
      <webElementGuid>413d9966-8152-4b4a-8f69-f2c3742e8d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freedom 500.000'])[1]/preceding::button[1]</value>
      <webElementGuid>052a8d64-e8ac-4821-b84d-44d90d6176a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulsa'])[4]/preceding::button[1]</value>
      <webElementGuid>690a3602-e32d-4e62-ad15-514ec9efa093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[2]/td[5]/div/button[2]</value>
      <webElementGuid>f3cb417e-14e4-48e0-9bb6-966fc7ce1392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[3]/table/tbody/td[5]/div/button[2]</value>
      <webElementGuid>d8d277c6-91e9-4d0f-876e-c785de42daa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulsa'])[2]/following::button[2]</value>
      <webElementGuid>fdf37623-8025-461c-94cf-ac00b94bce31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freedom 10.000'])[1]/following::button[2]</value>
      <webElementGuid>3a8543a7-4240-4593-9c81-526672270c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freedom 100.000'])[1]/preceding::button[1]</value>
      <webElementGuid>0dbb39cb-42cd-440c-abef-ad4b8a9b5339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulsa'])[3]/preceding::button[1]</value>
      <webElementGuid>45f61fe6-803f-47e1-a2bb-fa9bfdc56d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>8f9f7f32-7d98-450d-800e-2da733dadb66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
