<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>5e064652-4fcc-4cd8-86e4-e2ded5633a3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/form/div[7]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rowButton > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa15935c-b77a-4146-8dae-6f7774f3ffab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>c0e6b70a-e690-48e2-ba13-76a580d56361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;rowButton&quot;]/button[1]</value>
      <webElementGuid>deca358f-63b5-4495-bfd1-4947ff8fe72e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/form/div[7]/button</value>
      <webElementGuid>dd3ca29e-0a8b-4409-a94a-ba4e89164f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koin Transaksi'])[1]/following::button[1]</value>
      <webElementGuid>c41fdb27-4a4a-4306-83a1-7ecb7d1ef4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimal Transaksi'])[1]/following::button[1]</value>
      <webElementGuid>ead7b3a2-f47f-4c28-9301-9a1859976af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>0d0acc88-a90d-4721-bd3d-2e589b53db5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>9d2472e3-78a4-4326-b937-61ac53a834af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>78094e0d-67d5-414d-9991-40e43616eadb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
