<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reward Koin Transaksi_button_circle</name>
   <tag></tag>
   <elementGuidId>4643798b-83c2-44f5-acd8-635ef364a964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/div/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button_circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d2c22b0-1694-4055-8279-a8d64cdbc20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_circle</value>
      <webElementGuid>cf82438c-4d7f-4ef0-9297-a4e9193ed6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;produkSection&quot;]/div[@class=&quot;very_top&quot;]/div[@class=&quot;button&quot;]/button[@class=&quot;button_circle&quot;]</value>
      <webElementGuid>ceb2949a-e8e6-4619-a12f-ee7c6e1b95f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8086ce5-8187-4365-94b5-e09ca3c3faa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_circle</value>
      <webElementGuid>5e407d1f-4b13-4496-88c7-120f84ef5b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;produkSection&quot;]/div[@class=&quot;very_top&quot;]/div[@class=&quot;button&quot;]/button[@class=&quot;button_circle&quot;]</value>
      <webElementGuid>4207ae19-5023-4039-9860-fed4e1d59a4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div/div[2]/button[2]</value>
      <webElementGuid>ec43cf55-ec35-4329-b2a0-dbf6eefd0489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reward Koin Transaksi'])[1]/following::button[1]</value>
      <webElementGuid>970d5641-ae13-46cf-aa8f-a08594796816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[2]/following::button[2]</value>
      <webElementGuid>db93a25c-3692-4e59-9383-16bb2dc4ee8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Judul'])[1]/preceding::button[1]</value>
      <webElementGuid>6e9333b0-7797-41a7-9703-0c02b70b6bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/preceding::button[1]</value>
      <webElementGuid>9e785c33-2ae1-40b0-a9e1-a0511f5ace59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b55ec3ad-5eb8-4361-8d7d-0a3c357b42e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
