<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kontak</name>
   <tag></tag>
   <elementGuidId>f346e088-9ccd-4836-8d50-b7b3b80ca21b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div[2]/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb32e995-5512-4215-a231-661e2f140d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>80b6c4c2-50f8-40a2-a3eb-14a1caccabf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#kontak</value>
      <webElementGuid>3db51815-fd1c-40da-9fc1-47a4b4e34b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kontak</value>
      <webElementGuid>ea02c536-c1ea-47e0-9dd2-4d31c29d368c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;landingpage&quot;]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;right&quot;]/a[@class=&quot;nav&quot;]</value>
      <webElementGuid>0f247f24-9f5e-4675-afda-e3ec1d69ac1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div[2]/a[4]</value>
      <webElementGuid>d9b4c2de-91ac-4793-9345-75d3bea49093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kontak')]</value>
      <webElementGuid>a0e66c3f-c649-4b2b-974b-1360d5c73d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur'])[1]/following::a[1]</value>
      <webElementGuid>c259142a-3847-44fb-91d5-7771cff1b22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang'])[1]/following::a[2]</value>
      <webElementGuid>289590c6-6be9-4d58-ac3b-7ba42322403e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIGO (DIGital Outlet)'])[1]/preceding::a[1]</value>
      <webElementGuid>4b814d56-fbfb-47fa-989a-79b6a730b63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download app'])[1]/preceding::a[1]</value>
      <webElementGuid>b6769e92-28c5-41d3-b67b-e8e3df0f9b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kontak']/parent::*</value>
      <webElementGuid>a6107537-1487-414a-b012-6ec744b046fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#kontak')]</value>
      <webElementGuid>bd66c9bd-6e73-4053-82bd-6447128bb9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>d6cd6e85-a98e-4a56-9fe1-5d977a5cff15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#kontak' and (text() = 'Kontak' or . = 'Kontak')]</value>
      <webElementGuid>54111e41-1927-4e75-827b-fe34f5a32f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
