<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c245a26e-e115-424a-b2b4-7dc8f7390958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4182b4b-fad0-4c66-8dc9-5511701f6244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/logo.fde76f77d2fef9d45c8b2a0668dacdce.svg</value>
      <webElementGuid>a94d46f4-8318-42a9-a4ba-a52d2478c49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>ee7696f0-9cdc-4a85-8583-10bc3d62c18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;landingpage&quot;]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;left&quot;]/img[1]</value>
      <webElementGuid>2f2e5855-f800-42ca-addf-0bdcc681d7e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/img</value>
      <webElementGuid>79e4a835-f947-4feb-a93e-a1f46e8a3309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>7a55b215-d8bd-4a25-89a2-4d880414a8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fb58cf00-f492-4458-a4da-73d9626ffe12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/logo.fde76f77d2fef9d45c8b2a0668dacdce.svg' and @alt = 'logo']</value>
      <webElementGuid>0fe71357-b4f2-416c-affa-d10c1989e716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
