<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ProdukTagihanTop UpListrikKesehatanE_35fa38</name>
   <tag></tag>
   <elementGuidId>2c6f1e0f-7278-4688-bc67-8818f837e928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='category']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;category&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>833a68fc-4ac9-4759-ba92-654c47d127dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b430974-2189-41f6-bacf-f7f6cdafdaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>40df78c6-be61-4a55-8dcd-dfbf851eec34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProdukTagihanTop UpListrikKesehatanEntertainmentPulsaPaket Data</value>
      <webElementGuid>9a5c1f13-53ea-4058-9d15-3e0234bb256a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;produkSection&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;topRight&quot;]/select[@class=&quot;input&quot;]</value>
      <webElementGuid>39723b2d-4cb1-4ed3-8997-06f9649f8bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='category']</value>
      <webElementGuid>33cd70db-daa7-4c06-8af5-3b546f513491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/div[2]/select</value>
      <webElementGuid>97f5e6e6-0635-42b5-a12a-ef11e276c863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reward Koin Transaksi'])[1]/following::select[1]</value>
      <webElementGuid>46a4de7c-4285-491d-9304-033f3c81e490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[2]/following::select[1]</value>
      <webElementGuid>2669d456-0cde-410d-98bf-9e77800dc75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Judul'])[1]/preceding::select[1]</value>
      <webElementGuid>0a5e0ad2-a5fa-4bcf-8232-c5c98b25851c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/preceding::select[1]</value>
      <webElementGuid>81eff958-cbd3-4134-a410-12ecd2593819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ef916e4d-edfe-42d6-b317-5c1876cea04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'category' and (text() = 'ProdukTagihanTop UpListrikKesehatanEntertainmentPulsaPaket Data' or . = 'ProdukTagihanTop UpListrikKesehatanEntertainmentPulsaPaket Data')]</value>
      <webElementGuid>a9229fe4-aee7-4009-9be8-578a43189d28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
