<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kategori Produk.EntertainmentPulsaPa_1dfa42</name>
   <tag></tag>
   <elementGuidId>c255aea0-0a70-4dff-9401-46b7effa95ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='category_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;category_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0cdf3492-d981-49b3-96d1-d901b44759f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_id</value>
      <webElementGuid>b2defefb-5a2f-4af0-8562-6b2765af8046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...EntertainmentPulsaPaket DataHolidayWeeklyWeeklyHoliday</value>
      <webElementGuid>71eca51b-5166-4ccb-bf79-31a9db30deb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>6baf5f47-e81b-4ee4-8a47-1fc7d840229f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='category_id']</value>
      <webElementGuid>fbf34e2a-b41c-4b78-a4be-ddde13889c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/form/div[5]/select</value>
      <webElementGuid>0be09070-d842-4824-aba0-b03c158e0e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[2]/following::select[1]</value>
      <webElementGuid>0ae789b0-346b-4d30-8a1d-16e988ae0c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga (Rp)'])[1]/following::select[1]</value>
      <webElementGuid>bc35cc46-ecae-4d84-9e1c-e67a75f8b301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimal Transaksi'])[1]/preceding::select[1]</value>
      <webElementGuid>e90c0948-e465-4bad-8adc-ada38351c963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koin Transaksi'])[1]/preceding::select[1]</value>
      <webElementGuid>2f101911-20af-4a27-b3bd-a390693ce883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d4a5361f-904f-4337-bd5a-4f456418776a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'category_id' and (text() = 'Kategori Produk...EntertainmentPulsaPaket DataHolidayWeeklyWeeklyHoliday' or . = 'Kategori Produk...EntertainmentPulsaPaket DataHolidayWeeklyWeeklyHoliday')]</value>
      <webElementGuid>9329f0dd-f283-41da-ad9e-e04c341dda87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
