<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Holiday</name>
   <tag></tag>
   <elementGuidId>8c56aa28-8f05-4e4f-9359-7e4fae6cd00e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[6]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a096aeea-943d-4aa3-8054-74d178640423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Holiday</value>
      <webElementGuid>a1fb5f8c-1a4c-4bf5-bcf6-21f1a7a81209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;kategoriSection&quot;]/div[@class=&quot;bottom&quot;]/table[1]/tbody[6]/td[1]</value>
      <webElementGuid>3dafcaec-a4ca-4ac5-99bf-c0724a755e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/div[2]/table/tbody[6]/td</value>
      <webElementGuid>cb6990d2-0531-43d1-9f64-179041110eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Data'])[1]/following::td[2]</value>
      <webElementGuid>8ec555ad-8946-4673-aa49-8a2d6b8f7e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulsa'])[1]/following::td[4]</value>
      <webElementGuid>774388ae-efe8-4d22-a770-ba7e0087acf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Holiday']/parent::*</value>
      <webElementGuid>fe646358-b1fc-4ab5-a5af-d1a016a25a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[6]/td</value>
      <webElementGuid>8b25bbfa-58a6-44d8-a77e-a458191e4d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Holiday' or . = 'Holiday')]</value>
      <webElementGuid>c22303ab-dfac-4a2e-9614-59181ea5c1da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
