<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download app_phone</name>
   <tag></tag>
   <elementGuidId>d2f9e01f-c8ca-4e7c-8ed1-94a0df1c1058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='tentang']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2fce939f-bfb8-4506-9da3-f662cf3591f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>1bacfccf-bc79-4b72-b6de-e497316597c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/phone.3180bf94b7e28283dca3058bb90692a1.svg</value>
      <webElementGuid>700ca592-2900-466d-b217-4aa70e69c411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>8921a4ef-30fb-4c3a-914e-86c00e6580c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tentang&quot;)/div[@class=&quot;left&quot;]/img[@class=&quot;phone&quot;]</value>
      <webElementGuid>b1ce7963-7ff2-4d31-9e7b-03617ac7f31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f2adf578-d925-4aec-9264-8411b4036802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>e1ee6ab1-56b4-4de4-b9b7-cf9020a5519b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/phone.3180bf94b7e28283dca3058bb90692a1.svg</value>
      <webElementGuid>a47e89cf-2458-4838-9d2f-48a77a597b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>a34e4722-9e0d-473b-a951-8e11248566ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tentang&quot;)/div[@class=&quot;left&quot;]/img[@class=&quot;phone&quot;]</value>
      <webElementGuid>7d2a5ab9-d4e6-431b-afe1-613a978f1139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28f3b074-15a6-48da-af08-05b66f912663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>8d382c19-ccf9-49e2-83d5-2f4de949c548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/phone.3180bf94b7e28283dca3058bb90692a1.svg</value>
      <webElementGuid>f98d1e1e-eefe-4913-8551-1cd840faf2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>f3f1fee8-c43a-4200-a468-dc3c27ab66d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tentang&quot;)/div[@class=&quot;left&quot;]/img[@class=&quot;phone&quot;]</value>
      <webElementGuid>da3a67bb-b428-4aea-8e8e-f9f38c65bf21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='tentang']/div/img</value>
      <webElementGuid>c53e183f-8f70-4c7f-b88f-a84f5c99d006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='phone']</value>
      <webElementGuid>2e90ed79-ba33-4d47-bdd6-9e7b22595af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/img</value>
      <webElementGuid>ee82a1a2-bd4c-4729-b4b4-c52348b5e48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/phone.3180bf94b7e28283dca3058bb90692a1.svg' and @alt = 'phone']</value>
      <webElementGuid>ef15ae5e-162c-4d12-a306-8ebbb01e5a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
