<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>b3fd8703-6624-4913-a3fc-7f7d5fb51b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/div[3]/table/tbody[1]/td[7]/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/section/div[2]/div[2]/section/div[3]/table/tbody[1]/td[7]/div/button[2]</value>
      <webElementGuid>4d91de85-6d35-4ba2-b976-9fa03b5a8902</webElementGuid>
   </webElementProperties>
</WebElementEntity>
