<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kategori Produk.123as1232132132d</name>
   <tag></tag>
   <elementGuidId>fb4dbc3f-efc0-4000-babd-2fa2a788d1ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='kategori']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;kategori&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd60263f-ac4a-4c5f-9010-73e25bc6e408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>ea43ccba-5235-490a-ba08-803875c98af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>f857941c-a17f-4658-a05d-2ee66c34c5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>a0ccd380-4a34-4ccc-ae46-b73721614060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3063f445-caea-4036-9600-1e9d23430283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>fd7a651c-5c49-448b-950e-3328b2f2aff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>47d5e0af-c39d-42d7-b075-1ebf208656ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>9e93ddba-b438-48cf-b9b4-e148feda3d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cea8c546-c5a7-41b3-a902-0f6a01d1c0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>d076f5aa-a0ad-4ce4-9ba3-8548c06499b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>db49632f-48a7-45fd-9ed9-a1cf35363286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>a05e8100-c2ec-4ec2-941a-0bbe91eb0f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>29b5bab3-c9b4-4814-b52a-fc4e37ea8c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>dc0a1d10-0260-40f0-914c-74d656888000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>47b4f994-25a5-4079-bac6-70251b1b0519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>6c60d72b-31f6-4638-8e22-ee2697433d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c310360b-b9b0-49ca-8ca6-4b01903551d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>3ce199a4-585a-4846-a355-f5fb3cfa8cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>13f546a5-9c48-4bf4-8dc1-8e8a32e5c55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>7aed99b4-e042-4974-abe2-e38d44e2bf11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22cca6be-49d4-4167-a8e8-07441dfbb1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>3ed4c2f0-f213-4a75-a4c8-8ff73f801621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>f610e91c-be1f-4773-bb3d-f128b694c38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>4eee57b0-89a1-4973-aa8a-e1ac8f215101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bedcb46e-06fe-4223-bc41-28a87ae4e94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>b145b805-2ab6-4d54-8174-41b286509319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>7ca61df6-bfba-4cc6-9065-c38641bea2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>89d43d80-030b-4e7b-9635-5c56e6b23d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1bc01f51-0b66-4f79-a053-5c64d2306f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>5b107f25-92af-44fa-90c2-71c2e76c6702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Produk...123as1232132132d</value>
      <webElementGuid>26b2f80c-91da-4374-9247-571a23b87ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;sidebardashboard&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;content&quot;]/section[@class=&quot;addProdukSection&quot;]/form[@class=&quot;bottom&quot;]/div[@class=&quot;componentInput&quot;]/select[1]</value>
      <webElementGuid>a7bafd6e-7f01-40bb-b2d6-1f82895a85fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='kategori']</value>
      <webElementGuid>2988ea32-1a37-4b4a-8adc-b9878a1d7964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div[2]/section/form/div[2]/select</value>
      <webElementGuid>46436c48-4b1a-4e5c-9323-1c75f926530e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[2]/following::select[1]</value>
      <webElementGuid>7f2ab653-95e3-4990-b227-803c8905c0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[2]/following::select[1]</value>
      <webElementGuid>e3295d80-1f69-40b1-b405-13dc440504d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimal Transaksi'])[1]/preceding::select[1]</value>
      <webElementGuid>bd682dde-cc3e-4a6f-9898-74b1f8492d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koin Transaksi'])[1]/preceding::select[1]</value>
      <webElementGuid>6ad5278c-2003-4a5f-b15c-ff2153057015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c1bf7901-325e-4e34-b957-719ac5c524d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kategori' and (text() = 'Kategori Produk...123as1232132132d' or . = 'Kategori Produk...123as1232132132d')]</value>
      <webElementGuid>40876719-1b9d-4ee2-a440-395acb166b20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
