<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download app</name>
   <tag></tag>
   <elementGuidId>1aa504d0-a583-4624-8df7-0949d81b1cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;beranda&quot;]/div[1]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='beranda']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;beranda&quot;]/div[1]/button</value>
      <webElementGuid>e119983f-db67-48d5-99e1-799d6599a11d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='beranda']/div/button</value>
      <webElementGuid>e7b5a2be-8fb8-4b62-9ae0-e49de8b34e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIGO (DIGital Outlet)'])[1]/following::button[1]</value>
      <webElementGuid>b75086e9-167e-4dad-8c58-e7989e339d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontak'])[1]/following::button[1]</value>
      <webElementGuid>7a21c01c-ee58-4ead-b6d0-bbbb35bfa82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIGO app itu apasih?'])[1]/preceding::button[1]</value>
      <webElementGuid>ae08836d-b6a9-455f-86dc-8f78831f937d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sssstttt..... ada reward juga buat SOMI'])[1]/preceding::button[1]</value>
      <webElementGuid>1eda2ee4-443d-458c-9393-8f592b7f58a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download app']/parent::*</value>
      <webElementGuid>2f24b83b-9949-4efd-bbad-dd333b44797e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e8647c7e-0f91-41e4-9e79-b2c172c1c31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Download app' or . = 'Download app')]</value>
      <webElementGuid>6213cd99-d01f-45e4-bf52-b834b88cc44c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
