<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_DIGO (DIGital Outlet)</name>
   <tag></tag>
   <elementGuidId>fc229b6b-319b-4a15-b0d9-1e61deb50f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/nav/div[1]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='beranda']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/nav/div[1]/img</value>
      <webElementGuid>22339828-3d26-438d-988c-560ecb363191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='beranda']/div/h1</value>
      <webElementGuid>cf7763a0-7b43-4268-a3a1-aca98c0f7859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontak'])[1]/following::h1[1]</value>
      <webElementGuid>33159ed1-05b8-4e2a-9092-39bbb0846695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur'])[1]/following::h1[1]</value>
      <webElementGuid>ff35da80-f41f-4dfd-97b8-46c84076b372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download app'])[1]/preceding::h1[1]</value>
      <webElementGuid>ed4e9f9e-3765-489c-baaa-e69c8f3de930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIGO app itu apasih?'])[1]/preceding::h1[1]</value>
      <webElementGuid>bcd3d114-a625-4986-b7e2-0dea91b919b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIGO (DIGital Outlet)']/parent::*</value>
      <webElementGuid>44ffab13-df2d-484d-98c0-3ff356a49db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>47292cbc-0543-4ef7-949f-9ac59d8d9f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'DIGO (DIGital Outlet)' or . = 'DIGO (DIGital Outlet)')]</value>
      <webElementGuid>1ce5aa40-8251-4c01-998a-fd5965a20563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
